name: TCode
version: '${project.version}'
main: papka2017.tcode.TCode
api-version: '1.16'
authors: [Papka2017]
permissions:
  use:
    permission: tcode.use
    permission-message: "У вас нет прав для использования этой команды."
  reload:
    permission: tcode.reload
    permission-message: "У вас нет прав для использования этой команды."
commands:
  code:
    usage: /code
    permission: tcode.use
